version: "3.9"

services:
  flask-app:
    container_name: Pexon
    image: flask-app
    restart: always
    build:
      context: .
    ports:
      - 5001:5000
    volumes:
      - ./:/app
    environment:
      PORT: 5000
      FLASK_DEBUG: 1

volumes:
  database.db:
